/**
 * One-off: pull the latin + latin-ext subsets of the site's typefaces from
 * Google Fonts and self-host them.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Writes woff2 files into public/fonts/ and a @font-face sheet into
 * src/styles/fonts.css. Re-run only when the type stack changes — the output is
 * committed so builds never need the network.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = resolve(ROOT, 'public/fonts');
const SHEET = resolve(ROOT, 'src/styles/fonts.css');

// A modern desktop UA is required or the API serves ttf instead of woff2.
const UA =
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
    // Variable width + weight — the display face leans on the wdth axis.
    { query: 'Archivo:wdth,wght@75..125,400..700', slug: 'archivo' },
    { query: 'Martian+Mono:wght@500..700', slug: 'martian-mono' },
    { query: 'IBM+Plex+Mono:wght@400;500', slug: 'ibm-plex-mono' },
];

/** Only these subsets ship; the rest are dropped to keep the payload small. */
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const fetchText = async (url) => {
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
    return res.text();
};

await mkdir(FONT_DIR, { recursive: true });
await mkdir(dirname(SHEET), { recursive: true });

const blocks = [];

for (const { query, slug } of FAMILIES) {
    const css = await fetchText(`https://fonts.googleapis.com/css2?family=${query}&display=swap`);

    // The sheet is a flat list of `/* subset */ @font-face { ... }` pairs.
    const chunks = css.split(/\/\*\s*([a-z-]+)\s*\*\//i).slice(1);
    let index = 0;

    for (let i = 0; i < chunks.length; i += 2) {
        const subset = chunks[i].trim();
        const face = chunks[i + 1];
        if (!KEEP_SUBSETS.has(subset) || !face?.includes('@font-face')) continue;

        const remote = face.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
        if (!remote) continue;

        const file = `${slug}-${subset}-${index++}.woff2`;
        const res = await fetch(remote, { headers: { 'User-Agent': UA } });
        if (!res.ok) throw new Error(`${res.status} downloading ${remote}`);
        await writeFile(resolve(FONT_DIR, file), Buffer.from(await res.arrayBuffer()));

        blocks.push(
            `/* ${slug} · ${subset} */\n${face
                .replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('/fonts/${file}')`)
                .trim()}`
        );
        console.log(`  ✓ ${file}`);
    }
}

await writeFile(
    SHEET,
    `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n${blocks.join('\n\n')}\n`
);

console.log(`\nWrote ${blocks.length} @font-face rules to src/styles/fonts.css`);
